project:
  type: website
  render:  # only render index.qmd
    - "index.qmd"
  execute-dir: project  # working directory is always root of project
  output-dir: "_build/"

website:
  # Metadata (fill this in):
  title: "DWR Training Materials"
  search: false
  repo-url: "https://github.com/ucdavisdatalab/dwr"
  repo-actions: [issue, source]
  image: "images/datalab-logo-full-color-rgb.png"
  navbar:
    title: false
    logo: "images/datalab-logo-full-color-rgb.png"
    logo-alt: "The logo of the UC Davis DataLab."
    logo-href: "https://datalab.ucdavis.edu/"
    pinned: true  # always display

format:
  html:
    theme: cosmo
    toc: true
    include-in-header:
      - text: |
          <style>
          .navbar-logo {
            max-height: 3em;
            max-width: 50vw;
          }
          </style>
