project:
  type: website
  render:  # only render index.qmd
    - "index.qmd"
  execute-dir: project  # working directory is always root of project
  output-dir: "_build/"

website:
  # Metadata (fill this in):
  title: "DWR Training Materials"
  description: "Link tree for CA Department of Water Resources (DWR) training materials."
  search: false
  repo-url: "https://github.com/ucdavisdatalab/dwr"
  repo-actions: [issue, source]
  site-url: "https://ucdavisdatalab.github.io/dwr"
  favicon: "/images/datalab-logo_square_150x150.png"
  image: "/images/datalab-logo-full-color-rgb.png"
  image-alt: "The logo of the UC Davis DataLab."
  open-graph: true
  twitter-card: true
  navbar:
    title: false
    logo: "images/datalab-logo-full-color-rgb.png"
    logo-alt: "The logo of the UC Davis DataLab."
    logo-href: "https://datalab.ucdavis.edu/"
    pinned: true  # always display

format:
  html:
    theme: cosmo
    toc: true
    include-in-header:
      - text: |
          <style>
          .callout.callout-style-default .callout-body {
            padding: 0 1.5rem 0;
          }
          .navbar-logo {
            max-height: 3em;
            max-width: 50vw;
          }
          </style>
