---
title: "DWR Training Materials"
author:
  - name: "DataLab"
    url: "https://datalab.ucdavis.edu/"
    affiliations: "University of California, Davis"
date: today
---

:::{.callout-note title="Frequently Asked Questions"}

**Where can I find more information about DataLab workshops?**

Take a look at our [Workshop Descriptions and Materials
page][datalab-workshops].

[datalab-workshops]: https://datalab.ucdavis.edu/workshops/descriptions/

**How can I contact DataLab?**

Email [datalab@ucdavis.edu][].

For questions about a workshop you attended, you can also email the instructors
directly:

* Nick Ulle ([naulle@ucdavis.edu][])
* Pamela Reynolds ([plreynolds@ucdavis.edu][])

[datalab@ucdavis.edu]: mailto:datalab@ucdavis.edu
[naulle@ucdavis.edu]: mailto:naulle@ucdavis.edu
[plreynolds@ucdavis.edu]: mailto:plreynolds@ucdavis.edu
:::


## R Basics

* 10-4pm on Mar 5, 12 in [Shields 360][loc] and on Zoom
* [Workshop Reader][r-basics] ([PDF][pdf-r-basics])
* Live-coded notes:
    + [`2026-03-05_notes.R`][2026-03-05_notes]
    + [`2026-03-12_notes.R`][2026-03-12_notes]

[loc]: https://datalab.ucdavis.edu/location/
[r-basics]: https://ucdavisdatalab.github.io/dwr_workshop_r_basics/
[pdf-r-basics]: https://drive.google.com/file/d/1oW5RAoRgla-B8HtDSwD6g_UB_JCmPnG5/view?usp=sharing
[2026-03-05_notes]: https://github.com/ucdavisdatalab/dwr_workshop_r_basics/blob/main/notes/2026_dwr_training/2026-03-05_notes.R
[2026-03-12_notes]: https://github.com/ucdavisdatalab/dwr_workshop_r_basics/blob/main/notes/2026_dwr_training/2026-03-12_notes.R


## Intro to Reproducible and Collaborative Computational Practices, Part 1

* 10-5pm on Mar 19 in [Shields 360][loc] and on Zoom
* [Workshop Reader][research-computing]

[research-computing]: https://ucdavisdatalab.github.io/dwr_workshop_research_computing/


## Intermediate R

* All sessions are 10-noon in [Shields 360][loc] and on Zoom
* Standalone sessions (attend any or all):
    + Apr 2 -- Next-level Data Visualization (with ggplot2)
    + Apr 9, Apr 16 -- Cleaning & Reshaping Data
    + Apr 23 -- Best Practices for Writing R Scripts
    + Apr 30 -- Squashing Bugs with R's Debugging Tools
* [Workshop Reader][intermediate-r]
* Live-coded notes:
    + [`2026-04-02_notes.R`][2026-04-02_notes]
    + [`2026-04-09_notes.R`][2026-04-09_notes]
    + [`2026-04-16_notes.R`][2026-04-16_notes]

[2026-04-02_notes]: https://github.com/ucdavisdatalab/dwr_workshop_intermediate_r/blob/nu-dwr/notes/2026-04-02_notes.R
[2026-04-09_notes]: https://github.com/ucdavisdatalab/dwr_workshop_intermediate_r/blob/nu-dwr/notes/2026-04-09_notes.R
[2026-04-16_notes]: https://github.com/ucdavisdatalab/dwr_workshop_intermediate_r/blob/nu-dwr/notes/2026-04-16_notes.R

[intermediate-r]: https://ucdavisdatalab.github.io/dwr_workshop_intermediate_r/
